apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: echo
        image: gitlab.cloud-observability.akadns.net:5050/kupala/sqa_registry:latest
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 600']
      restartPolicy: Never
  backoffLimit: 0
