apiVersion: v1
kind: Secret
metadata:
  name: gitlab-access-token
type: Opaque
data:
  token: Z2xwYXQtRFFKUGJ6Nmp2V1J4MXF0SnRwYncK
---
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    podSpec:
      containers:
      - name: echo
        image: gitlab.cloud-observability.akadns.net:5050/kupala/sqa_registry:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        imagePullSecrets:
            - name: gitlab-registry-secret
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 600']