apiVersion: v1
kind: Secret
metadata:
  name: gitlab-access-token
type: Opaque
data:
  token: Z2xwYXQtRFFKUGJ6Nmp2V1J4MXF0SnRwYncK
---
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: echo
        image: grafana/grafana:latest
        imagePullPolicy: Always
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 600']
      restartPolicy: Never
  backoffLimit: 0