apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: argocd  # Namespace where ArgoCD is deployed
spec:
  destination:
    namespace: argocd  # Namespace where you want to deploy Grafana
    server: https://kubernetes.default.svc  # The Kubernetes API server URL
  source:
    repoURL: https://github.com/syedmoin777/argocd-example-apps.git  # Replace with your Git repository URL
    targetRevision: master  # Replace with your desired Git branch/tag
    path: grafana-post-sync  # Path to your Grafana deployment YAML files
    
  project: default  # ArgoCD project to associate this application with
  syncPolicy:
    automated:
      prune: true  # Optionally, to prune resources not in the Git repository
  postSync:
    hooks:
      - name: health-check
        hookType: Bash
        manifest: |
          #!/bin/bash
          kubectl rollout status deployment/grafana -n default
